### ISSUE TITLE
Handling multiple text nodes

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/streaming-include#1]
```js
const parser = new DOMParserStream();
const writer = parser.writable.getWriter();
writer.write('Hello ');
writer.write('world!');
```

In this case the HTML parser will create a text node for "Hello ", then change the data of that text node to "Hello world!". But what should `DOMParserStream` do?

**1. Emit one text node, but silently update it**

The whole design of `DOMParserStream` tries to avoid this. It's especially problematic if the user has transformed the stream to map the nodes to something else. Now they won't see the change.

**2. Emit one text node, then some kind of update instruction**

Right now `ParserChunk` is really simple. It gives you a node and tells you where to put it. Instead, we could make it something like:

```ts
interface ParserChunk {
  add: {
    node: Node,
    parent: Node | null,
    nextSibling Node | null,
  } | null;
  changeText: {
    node: Text,
    text: string,
  } | null;
}
```

With each parser chunk, one of *add* or *changeText* will be null. This isn't as nice to deal with, but it's still nicer than mutation records.

**3. Emit two text nodes**

In this model, combining text nodes can to be done later, perhaps by `DOMWritable`.

This gets complicated if text nodes end up moving due to a parsing error, as the reference document will now have one text node, but we need to emit a `ParserChunk` to move each text node we created as a result.

If `DOMWritable` is merging text nodes, it would need to ignore chunks about a text node it's discarded.

**4. Buffer text**

We could hold onto text until we know it's complete (presumably because another kind of node has appeared). This reduces the opportunity for progressive rendering, but it's unusual to have long runs of text.

We'll need to do this for `<script>` and `<style>` anyway, so the logic will already be part of the polyfill.

**Comment by jakearchibald** [comment]
@domenic Interested in your thoughts on this.

**Comment by domenic** [comment]
> 3. Emit two text nodes

This seems simplest.

> This gets complicated if text nodes end up moving due to a parsing error, as the reference document will now have one text node, but we need to emit a ParserChunk to move each text node we created as a result.

Can you provide an example of the scenario you're envisioning? If I've got it right in my head, then it doesn't seem too bad to handle as a consumer. But it may imply that we need to track previously-vended text nodes so that we can emit a move instruction, which is annoying. If we need that complexity anyway, then 1 or 2 is may not be so bad.

> 4. Buffer text

Actually, this seems pretty darn simple too. My intuition, vaguely guided by jsdom bug reports, is that the longest runs of text are precisely those inside `<style>` and `<script>`. If we have to buffer those anyway, then I am having a hard time imagining other long runs of text. So this could work great.

So yeah, maybe just do (4)!

**Comment by jakearchibald** [comment]
> Can you provide an example of the scenario you're envisioning?

```html
<b><p>Bold</b> 
<!-- becomes… -->
<b></b><p><b>Bold</b>
```

Say this is emitted char by char. We emit "B", "o", "l", "d" text nodes, then emit them all again in their new position.

If the processor has logic like "If this text node is being inserted after another text node, discard it and add its value to the previous text node", but since those nodes are going to be emitted twice, you could end up with "Boldold", unless you're tracking discarded nodes, like this example with `discardedNodes`:

```js
class DOMWritable extends WritableStream {
  /**
   * @param {Element} target
   */
  constructor(target) {
    const discardedNodes = new WeakSet();

    super({
      write({node, nextSibling, parent}) {
        if (discardedNodes.has(node)) return;

        // If we're adding a text node next to another text node, combine their values
        const previousSibling = nextSibling ? nextSibling.previousSibling : (parent || target).lastChild;
        if (node.nodeType === 3 && previousSibling && previousSibling.nodeType === 3) {
          previousSibling.nodeValue += node.nodeValue;
          discardedNodes.add(node);
        } else {
          (parent || target).insertBefore(node, nextSibling);
        }
      }
    });
  }
}
```

If you don't, then you might see

**Comment by jakearchibald** [comment]
I'm going to do option 4 and see how it goes.
