### ISSUE TITLE
What to do about </template>

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/streaming-include#3]
If the incoming stream contains `</template>` without an opening tag, it breaks out of the document we're using to monitor incoming elements.

I'm worried there isn't a way around this.

**Comment by domenic** [comment]
As an implementation hack we could scan for the `</template>` string and then treat it as a bogus close tag (I assume that means throwing it away?).

**Comment by jakearchibald** [comment]
Interesting. I'd need to split the incoming string after `<template>` (plus attributes) so I can see if it creates a `<template>` element, since `</template>` is ok in that case.

Gets complicated if `</template>` appears in script, or a comment etc etc.

**Comment by domenic** [comment]
> Interesting. I'd need to split the incoming string...

Maybe I'm not understanding, but it seems like you could get away with an incrementing/decrementing counter.

> Gets complicated if `</template>` appears in script, or a comment etc etc.

Yeah, I guess you'd need to know what parser or at least tokenizer state you are in to know whether this is a bogus end tag or something else. (E.g., text content.) Reproducing that logic is not great. Hmm.

---

What if you didn't use a template wrapper at all? For example if the wrapper were the html/body tags, then [it seems](http://software.hixie.ch/utilities/js/live-dom-viewer/) like the browser will discard bogus end tags for us. body as a wrapper seems relatively OK, given DOMParser precedent.

**Comment by domenic** [comment]
@jakearchibald quick ping to see if you have any thoughts on a body wrapper instead of template wrapper? We may want to brainstorm on this a bit when we're both online some time soon.

**Comment by jakearchibald** [comment]
Sorry for the delay. Yeah, this sounds interesting. You lose the ability to stream in a set of table rows, although I guess you can work around it. I'll do some testing…

**Comment by jakearchibald** [comment]
Yeah, this works https://github.com/jakearchibald/streaming-include/commit/13bf57330f200f61cd96dc34ad4254df160356bb

I was worried about `</body>`, `</html>` and also about things like `<img>` loading, but it seems fine.
